# Generated by Django 4.2.7 on 2023-11-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dentist_name', models.CharField(max_length=10000)),
                ('clinic_name', models.CharField(max_length=10000)),
                ('clinic_address', models.CharField(max_length=10000)),
                ('city_town', models.CharField(max_length=10000)),
                ('province', models.CharField(max_length=1000)),
                ('region', models.CharField(max_length=1000)),
                ('zipcode', models.IntegerField()),
                ('contact_number', models.CharField(max_length=10000)),
                ('clinic_schedule', models.CharField(max_length=10000)),
            ],
        ),
    ]
