# Generated by Django 4.2.7 on 2023-11-30 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dentist_name', models.CharField(max_length=10000, null=True)),
                ('clinic_name', models.CharField(max_length=10000, null=True)),
                ('clinic_address', models.CharField(max_length=10000, null=True)),
                ('city_town', models.CharField(max_length=10000, null=True)),
                ('province', models.CharField(max_length=1000, null=True)),
                ('region', models.CharField(max_length=1000, null=True)),
                ('zipcode', models.IntegerField(null=True)),
                ('contact_number', models.CharField(max_length=10000, null=True)),
                ('clinic_schedule', models.CharField(max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dentist_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'app_dentist_schedule',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=1000)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True)),
                ('response', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
